### ISSUE TITLE
Random module

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/bavi#14]
* Most used feature is `.choose thing1|thing2|thing3|...`
  * Other randomness features (dice roll, random number, etc.) are usually covered by the IRC network's `GameServ` bot

**Comment by dinsfire64** [comment]
I'm going to hit the coffee shop this afternoon and knock this out.

**Comment by dinsfire64** [comment]
Request close after merge commit 15dcf71e6076f4c4dcf34819a4ceeaec1db7f707.
